// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDypZ1PKa7f-TgW87FVsgsk4HupK0OyiAM',
    appId: '1:158860184192:web:cf272f6c03fb2893b7f465',
    messagingSenderId: '158860184192',
    projectId: 'town-squar-a60f7',
    authDomain: 'town-squar-a60f7.firebaseapp.com',
    storageBucket: 'town-squar-a60f7.firebasestorage.app',
    measurementId: 'G-FXXY90RMVF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAspfbLFf-HR3UFKbyj46LfRvl4kO8y1NE',
    appId: '1:158860184192:android:545069db0b6190beb7f465',
    messagingSenderId: '158860184192',
    projectId: 'town-squar-a60f7',
    storageBucket: 'town-squar-a60f7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoA8OhEVR3bcz0xZca3B_839lXmgIjV-M',
    appId: '1:158860184192:ios:a9728cd7f560ad00b7f465',
    messagingSenderId: '158860184192',
    projectId: 'town-squar-a60f7',
    storageBucket: 'town-squar-a60f7.firebasestorage.app',
    iosBundleId: 'com.townSquar',
  );
}
